name=CogefinActuatorHAL
version=0.1
author=houtbrion@gmail.com
maintainer=houtbrion@gmail.com
sentence=Hardware abstraction layer library for IoT actuator
paragraph=A hardware abstraction layer library for IoT actuator
category=actuator
url=https://github.com/houtbrion/CogefinActuatorHAL
architectures=*
